name: Node.js CI

on:
  push:
    branches: [ master, dev ]
    paths:
      - "ui/**"
  pull_request:
    branches: [ master, dev ]
    paths:
      - "ui/**"

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - run: npm ci
    - run: npm run build
